### ISSUE TITLE
This Project Really help me!

### ISSUE THREAD

**Issue by Sernorita** [mehmet-yilmaz/netplan-dbus-example#1]
First of all, I am very confused to embed the netplan api in my C++ project, cause I need to configure my device's IP to be static by "networkd", I choose the netplan as the breakthrough point, but when I read the official site I am shocked that the libnetplan api seems not support to a function to write the netplan related ".yaml" to "networkd" related files into the path such as /run/systemd/network/*.yaml (Ubuntu22.03 LTS), so I gave up use libnetplan, even thought I should change another "Network Manage" front end to help me, until I found this project. 
I have integrated your excellent project into my personal project, and I have found that when use dbus to do "Apply()" operation, the temperary dbus path such as "S1OZ5V" will change, so you need to restart the connect() function, this "connect" function is in the constructor of NetplanService Class, so I reuse this function as soon as ApplyConfiguration is finished.
Thank you a lot!  Best wishes to you!

**Comment by mehmet-yilmaz** [comment]
I am pleased to hear this helps you.
Thanks for all your best wishes and I also wish all my best.
